vscode:
  extensions:
    - golang.go

tasks:
  - name: Install Delve
    init: >
      GOBIN=/tmp/ go install github.com/go-delve/delve/cmd/dlv@master &&
      mkdir -p $GOPATH/bin/ &&
      mv /tmp/dlv $GOPATH/bin/dlv-dap &&
      open https://gitpod-choclate-fox-app.dev.razorpay.in/

ports:
  - port: 8080
    onOpen: open-browser
    visibility: private