name: Gitpod
on:
  push:
    paths:
      - 'example/gitpod/**'

jobs:
  gitpod:
    runs-on: ubuntu-latest
    name: Build Gitpod app
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # always uses a single image ,the changes are overridden
        # to-do versioning of the builds in case required
      - name: build configurator
        uses: docker/build-push-action@v2
        with:
          tags: abhay2134/devstack:${{ github.sha }}
          push: true
          file: ./example/gitpod/Dockerfile
